### ISSUE TITLE
OpenURI::HTTPError: 401 Unauthorized

### ISSUE THREAD

**Issue by JackiMode** [dlt/yahoo_weatherman#16]
```
2.2.0 :001 > require 'yahoo_weatherman'
 => true
2.2.0 :002 > client = Weatherman::Client.new
 => #<Weatherman::Client:0x000000018dda50 @options={}, @uri="http://weather.yahooapis.com/forecastrss">
2.2.0 :003 > response = client.lookup_by_woeid 455821
OpenURI::HTTPError: 401 Unauthorized
        from /usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open-uri.rb:358:in `open_http'
        from /usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open-uri.rb:736:in `buffer_open'
        from /usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open-uri.rb:211:in `block in open_loop'
        from /usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open-uri.rb:209:in `catch'
        from /usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open-uri.rb:209:in `open_loop'
        from /usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open-uri.rb:150:in `open_uri'
        from /usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open-uri.rb:716:in `open'
        from /usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open-uri.rb:34:in `open'
        from /usr/local/rvm/gems/ruby-2.2.0/gems/yahoo_weatherman-2.0.0/lib/yahoo_weatherman.rb:74:in `get'
        from /usr/local/rvm/gems/ruby-2.2.0/gems/yahoo_weatherman-2.0.0/lib/yahoo_weatherman.rb:47:in `lookup_by_woeid'
        from (irb):3
        from /usr/local/rvm/rubies/ruby-2.2.0/bin/irb:11:in `<main>'

```

**Comment by Omnihuron** [comment]
Yahoo now requires an API key for their weather. 
https://developer.yahoo.com/weather/

I may take a shot at updating this gem tomorrow.

**Comment by JackiMode** [comment]
W dniu 2016-03-31 o 21:15, Allan McLelland pisze:
> Yahoo now requires an API key for their weather.
> https://developer.yahoo.com/weather/
>
> I may take a shot at updating this gem tomorrow.

That would be very nice. I'm ruby begginer, so my trial to modyfiy your 
gem has failed.
My workaround to get current conditions works pretty well:

url = 
'https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20=519212%20&format=json'
uri = URI(url)
response = Net::HTTP.get(uri)

json_response = JSON.parse(response)
condition = 
json_response['query']['results']['channel']['item']['condition']

But Your gem is much priettier sollution. Thank You

Regards

**Comment by amclelland** [comment]
Hey @JackiMode, I opened a PR for this fix. You can use my fork in the meantime if it's urgent by editing your gemfile with this line:
`gem 'yahoo_weatherman', github: 'amclelland/yahoo_weatherman'`

**Comment by yonigozman** [comment]
Properly fixed the issue by migrating to yahoo's new api, and converting parsing to json from XML as a bonus :)

https://github.com/yonigozman/yahoo_weatherman

opening a PR
